name: Release Ska Package
on:
  workflow_call:
    inputs:
      repository:
        description: Repository being released
        required: false
        type: string
        default: ${GITHUB_REPOSITORY}
      sha:
        description: sha of the release
        required: false
        type: string
        default: ${GITHUB_SHA}
    secrets:
      SKARE3_CI_API_TOKEN:
        required: true

jobs:
  patch-release:
    runs-on: ubuntu-latest
    name: Patch Release
    steps:
    - name: Fetch Skare3 Tools
      uses: actions/checkout@v3
      with:
        repository: sot/skare3_tools
        ref: master
        path: skare3_tools
    - name: Release Description and Skare3 Issue
      run: |
        sudo -H pip3 install setuptools wheel
        sudo -H pip3 install -r ./skare3_tools/requirements.txt
        sudo -H pip3 install ./skare3_tools
        skare3-release-merge-info --repository ${{ inputs.repository }} --sha ${{ inputs.sha }}
        skare3-create-issue --repository sot/skare3 --latest-release ${{ inputs.repository }} --label 'Package update'
      env:
        GITHUB_API_TOKEN: ${{ secrets.SKARE3_CI_API_TOKEN }}
